<?php

########################################################################
# Extension Manager/Repository config file for ext: "nboevents"
#
# Auto generated by Extension Builder 2012-10-09
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Kurse und Reisen',
	'description' => 'Create Events and Register Persons',
	'category' => 'plugin',
	'author' => 'Noel Bossart',
	'author_email' => 'n.company@me.com',
	'author_company' => 'noelboss.ch',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>